global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodo_juegos'
    static_configs:
      - targets: ['192.168.0.202:9100']

  - job_name: 'nodo_storage'
    static_configs:
      - targets: ['192.168.0.201:9100']

  - job_name: 'nodo_propio'
    static_configs:
      - targets: ['192.168.0.203:9100']

  - job_name: 'nodo_DNS'
    static_configs:
      - targets: ['192.168.0.205:9100']
